export const meals = [
  {
    id: 1,
    name: "Classic Spaghetti Carbonara",
    description:
      "A quick and easy Italian pasta dish with a creamy egg sauce and pancetta.",
    ingredients: [
      "100g pancetta",
      "50g pecorino cheese",
      "50g parmesan",
      "3 large eggs",
      "350g spaghetti",
      "2 plump garlic cloves, peeled and left whole",
      "50g unsalted butter",
      "sea salt and freshly ground black pepper",
    ],
    steps: [
      "Put a large saucepan of water on to boil.",
      "Finely chop the pancetta, having first removed any rind.",
      "Finely grate both cheeses and mix them together.",
      "Beat the 3 large eggs in a medium bowl and season with a little freshly grated black pepper.",
      "Add the spaghetti to the water and cook according to packet instructions.",
      "Squash the garlic with the blade of a knife, just to bruise it.",
      "While the spaghetti is cooking, fry the pancetta with the garlic.",
      "Remove the garlic from the pan and discard.",
      "Drain the spaghetti and add to the pan with the pancetta.",
      "Take the pan of spaghetti and pancetta off the heat.",
      "Quickly add the eggs and cheese.",
      "Mix everything together well.",
    ],
  },
  {
    id: 2,
    name: "Homemade Margherita Pizza",
    description:
      "A simple yet delicious Margherita pizza with homemade dough and fresh ingredients.",
    ingredients: [
      "300g strong bread flour",
      "1 tsp instant yeast",
      "1 tsp salt",
      "1 tbsp olive oil",
      "100ml passata",
      "handful fresh basil leaves",
      "125g ball mozzarella",
      "handful grated or shaved parmesan",
      "extra virgin olive oil",
    ],
    steps: [
      "Make the dough by mixing flour, yeast, and salt with water and olive oil.",
      "Knead to a smooth dough and leave to rise.",
      "Heat oven to its highest setting.",
      "Roll out the dough thinly.",
      "Spread passata over the base.",
      "Tear over the mozzarella and scatter with basil leaves.",
      "Drizzle with olive oil and season.",
      "Bake for 8-10 minutes until crisp.",
    ],
  },
  {
    id: 3,
    name: "Classic Caesar Salad",
    description:
      "A fresh and tasty salad with homemade Caesar dressing, croutons, and parmesan.",
    ingredients: [
      "1 garlic clove",
      "2 anchovy fillets",
      "medium block of parmesan or Grana Padano cheese for shaving",
      "2 eggs",
      "sunflower oil",
      "1 tbsp white wine vinegar",
      "1 large cos or romaine lettuce",
      "1 small baguette",
      "olive oil",
    ],
    steps: [
      "Make the dressing by crushing garlic and anchovies.",
      "Add grated parmesan, egg yolks, vinegar, and oil to make a creamy sauce.",
      "Season the sauce with salt and pepper.",
      "Tear the lettuce into large pieces.",
      "Cut the baguette into small cubes and fry with oil to make croutons.",
      "Toss the lettuce with the dressing, croutons, and extra parmesan shavings.",
    ],
  },
];
